import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GlobalContainer from './containers/global_container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'SFO For Agent',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GlobalContainer>{children}</GlobalContainer>
            </body>
        </html>
    );
}
